### ISSUE TITLE
Support connecting to UNIX sockets

### ISSUE THREAD

**Issue by bearcatsandor** [ambientsound/pms#111]
version: current git as of 20180210

MPD_HOST=/home/moonwind/.config/mpd/socket
MPD_PORT=6600

ls /home/moonwind/.config/mpd includes
 srw-rw-rw- 1 moonwind moonwind    0 Jan  4 15:54 socket

My debug gives me:
[1.01009] Establishing MPD IDLE connection to /home/moonwind/.config/mpd/socket:6600...
[1.01097] ERROR: Error connecting to MPD: MPD connection error: dial tcp: lookup /home/moonwind/.config/mpd/socket: no such host

Ncmpcpp uses that socket just fine, so i'm not sure what's happening here. Is pms unable to use sockets?

**Comment by ambientsound** [comment]
That's right, unfortunately. Connecting to a socket is not supported presently.

**Comment by bearcatsandor** [comment]
Thank you. I hope that it's supported someday. In the mean time, I realized that I can activate both  the socket and the http port. It seems to lose that connection from time to time, and the elapsed time doesn't reset when going to a new track. These may or may not be related issues.

**Comment by bearcatsandor** [comment]
Thank you. I hope that it's supported someday. In the mean time, I realized that I can activate both  the socket and the http port. It seems to lose that connection from time to time, and then the elapsed time doesn't reset when going to a new track. These may or may not be related issues.

**Comment by bearcatsandor** [comment]
Thank you!
