### ISSUE TITLE
Vim-like selection with shift + v

### ISSUE THREAD

**Issue by nicholasglazer** [ambientsound/pms#115]
I checked `man` and issues on gh, but didn't found multiselect. Wonder if it's implemented or not?

**Comment by tremby** [comment]
Presuming you're using the Go version, you can press `v` for visual selection mode. Then move up or down and you'll see the selection.

**Comment by tremby** [comment]
Not sure where that 0.99 version number came from, but that commit hash points to [this](https://github.com/ambientsound/pms/commit/8c89184), which is the (very) old C++ version, and is actually part of the 0.42 line.

So the answer is yes, it's implemented. It's at least implemented in the current version, but I don't remember if it exists in the 0.42 branch.
