### ISSUE TITLE
Change playing speed.

### ISSUE THREAD

**Issue by b00sher** [ambientsound/pms#125]
Hi, I read [doc/commands.md](https://github.com/ambientsound/pms/blob/master/doc/commands.md) and didn't find a way how to increase/decrease playing speed. 

(1) Can _pms_ do that? 
(2) Can _mpd_ do that?

If (1) true, then how?
If (1) false and (2) true, then can you implement this?
If (2) false, then well, it sucks.

**Comment by ambientsound** [comment]
As far as I know, there is no way of choosing playback speed with MPD. Also found an open issue for this at MusicPlayerDaemon/MPD#46. If it is ever implemented in MPD, it would be a small task to add it to PMS as well. For now, closing this issue.
