### ISSUE TITLE
Display/Sorting Issues

### ISSUE THREAD

**Issue by pfish** [ambientsound/pms#19]
Updated over to the latest git head of both pms and libmpdclient. After the update, pms started to behave very interestingly: the tags it displays are wrong, for instance the track number is not displayed properly but in its stead some sort tag is shown. Moreover, the sorting seems wonky, too.

The picture below should illustrate these issues.
![desktop](https://cloud.githubusercontent.com/assets/421215/9703896/8bfde4c6-5499-11e5-8990-061bd8f57564.jpg)

**Comment by ambientsound** [comment]
This seems very strange. My best guess is that you are using the header files for libmpdclient 2.11, but still linked against the old version. Could you ensure that the newest version is the only one installed?

**Comment by pfish** [comment]
Thanks for the heads-up. Recompiling solved the issue and now everything works as it's supposed to!

**Comment by ambientsound** [comment]
Glad it worked out! :smile:
