### ISSUE TITLE
Replace old manual page with new Markdown-based version

### ISSUE THREAD

**Issue by lahwaacz** [ambientsound/pms#20]
There are [pms.1](https://github.com/ambientsound/pms/blob/master/pms.1) and [manpage.md](https://github.com/ambientsound/pms/blob/master/doc/manpage.md). I guess the former is outdated, because the example for configuring the topbar does not work anymore. Is there a reason why the old one is still included during the build process?

**Comment by ambientsound** [comment]
You are correct, the former is outdated and should be removed. It is still included because it is undecided whether the auto-generated `pms.1` (from `manpage.md`) should be part of the repository or not. If not, compiling and installing will require having `pandoc` installed.

**Comment by lahwaacz** [comment]
If pandoc is too heavyweight, you could try [md2man](https://github.com/sunaku/md2man) or possibly some other tool for the conversion.

**Comment by ambientsound** [comment]
Thanks for the suggestion. I don't really consider `pandoc` too heavyweight. The requirement should probably be that `pms.1` is generated when running `make dist`, and I need to figure out how to configure autoconf and automake to do this.
