### ISSUE TITLE
Wrong column widths in playlist

### ISSUE THREAD

**Issue by lahwaacz** [ambientsound/pms#21]
The algorithm for adjusting width of columns in the playlist does not take into account the data to be displayed. If the song title is too long, its column will span most of the screen, leaving only a few characters for the artist column in some cases, regardless of the actual length of the artist text. And the track number column displays only one digit.

**Comment by lahwaacz** [comment]
With a 22-song album in the playlist, the "No" column displays the following:
```
1 
2 
3 
4 
5 
6 
7 
8 
9 
1 
11
12
13
14
15
16
17
18
19
2 
21
22
```
Somehow the trailing zeros are stripped...

**Comment by ambientsound** [comment]
Hi @lahwaacz. Which version are you running? Do you mind posting a screenshot?

**Comment by lahwaacz** [comment]
[This condition](https://github.com/ambientsound/pms/blob/master/src/song.cpp#L164) is wrong, you have probably intended to strip _leading_ zeros, but the code in fact ignores zeros at _any_ position.

I will try to reproduce the problem with column widths and post a screenshot when my current playlist ends.

**Comment by lahwaacz** [comment]
The screenshots: it looks fine in [fullscreen](http://postimg.org/image/yo8y83pap/), but you can see the issue in [half-split screen](http://postimg.org/image/pf6rxzgep/) -- the artist column disappeared completely, leaving only the overly-wide title column.

**Comment by ambientsound** [comment]
Great, thanks for the screenshots. I'll look into the issue. This is running on the latest master commit, right?

**Comment by lahwaacz** [comment]
Right.

**Comment by ambientsound** [comment]
Sorry about bumping this old thread. This bug is unlikely to get fixed in the old version. There is a new master version where this glitch is not present. Feel free to give it a go?

**Comment by lahwaacz** [comment]
I don't use pms anymore, so if you say it's fixed in master, I have no problem closing this.
