### ISSUE TITLE
Reordering songs in playlist

### ISSUE THREAD

**Issue by lahwaacz** [ambientsound/pms#22]
In some older version, it was possible to move selected song up (down) by just holding a `K` (`J`) key. Now when you press `K`, the selected song is swapped with the above, but the focus remains on the same row, so holding the `K` key swaps always the same two songs. Is this a bug or feature?

Also, I would appreciate a way to apply different ordering for playlist and the library when adding entire albums, or to apply specific ordering to the existing playlist. The use case is adding a multi-artist album from a library sorted by artist and sorting it by track number in the playlist. I apologize if this is already possible and I haven't figured it out...

**Comment by ambientsound** [comment]
I'm unsure about the first issue. I think it might be a regression. Which versions are you comparing?
As for the second feature, I plan on implementing a `:sort` command that one can use to sort the current selection (or entire list).

**Comment by lahwaacz** [comment]
My current version is as of 3e476e9. I'm not sure about the previous version because I don't have the package anymore, but it is about a year back. I could dig in my backups it it's important.

**Comment by ambientsound** [comment]
OK, but the previous version is actually packaged? It probably means that it's 0.41 or 0.42.

In any case, these are two separate issues. I added the `:sort` request in #24.

Sorry about lagging behind on answers and patches. I am currently rewriting the whole window management code, which is hundreds upon thousands of lines, so things are going a bit slow at the moment :)

**Comment by riggs-** [comment]
The legacy branch is no longer maintained, closing for now.
