### ISSUE TITLE
aclocal problems

### ISSUE THREAD

**Issue by daniellacoste** [ambientsound/pms#25]
Trying to install PMS as a client on my iMac to access a Raspberry Pi server with MPD. 

I am trying to run the ./rebuild.sh command to build the environment but I received an 'aclocal: command not found' error. I used Homebrew to install automake, which contains the aclocal command. Now, when running the rebuild file I am given:
     "You should update your 'aclocal.m4' by running aclocal."
     ...

Running aclocl I receive:

configure.ac:41: warning: macro 'AM_GNU_GETTEXT' not found in library
configure.ac:40: warning: AM_NLS is m4_require'd but not m4_defun'd
/usr/local/share/aclocal/intltool.m4:160: IT_PROG_INTLTOOL is expanded from...
configure.ac:40: the top level
configure.ac:40: warning: AM_NLS is m4_require'd but not m4_defun'd
m4/intltool.m4:160: IT_PROG_INTLTOOL is expanded from...
configure.ac:40: the top level

Also my ./configure && make will not work either:
configure: error: cannot find install-sh or install.sh in . ./.. ./../.. 

(if this matters) In addition to automake, I have libtool, gettext, and autoconf installed - how come my ./configure cannot find the install-sh or install.sh files?

Sorry if this sounds irrelevant to PMS (I am new to this).

**Comment by delacost** [comment]
also, from the INSTALL file, I did as it instructed:
intltoolize --force
aclocal -I m4
autoreconf --force --install --verbose

the first command I receive: 
You should update your 'aclocal.m4' by running aclocal.

then I run 'aclocal' and get:
configure.ac:41: warning: macro 'AM_GNU_GETTEXT' not found in library
configure.ac:40: warning: AM_NLS is m4_require'd but not m4_defun'd
/usr/local/share/aclocal/intltool.m4:160: IT_PROG_INTLTOOL is expanded from...
configure.ac:40: the top level
configure.ac:40: warning: AM_NLS is m4_require'd but not m4_defun'd
m4/intltool.m4:160: IT_PROG_INTLTOOL is expanded from...
configure.ac:40: the top level

what exactly am i doing wrong? 
thanks :)

**Comment by ambientsound** [comment]
Hi @delacost,

As far as I can see there are several issues here. Some m4 macros are missing from the autoconf/automake distribution. I don't know about the `install` files but maybe you need to resolve the m4 problem first.

The problems are not related to the PMS source code itself, but to the autotools configuration, so you might try to google the error messages to see what may be wrong.

I'll give it a shot and see if I can get it compiled on Mac OS X though.

Regards

**Comment by delacost** [comment]
Hey @ambientsound 

Any luck compiling it on Mac OS X? I've left this alone for the past 2 wks but I"m looking to go back and finishing the installation ... I really want this to work because I think PMS looks great!
Cheers,
D

**Comment by ambientsound** [comment]
Hi, sorry about the delay. I tried to copy a bunch of files from my Linux aclocal distribution into `m4/` in the PMS source code directory:

```
	m4/gettext.m4
	m4/iconv.m4
	m4/lib-ld.m4
	m4/lib-link.m4
	m4/lib-prefix.m4
	m4/nls.m4
	m4/po.m4
	m4/progtest.m4
```

Now, I get this output when running `rebuild.sh`:

```
$ ./rebuild.sh
You should update your 'aclocal.m4' by running aclocal.
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force
configure.ac:41: warning: macro 'AM_GNU_GETTEXT' not found in library
configure.ac:40: warning: AM_NLS is m4_require'd but not m4_defun'd
/usr/local/share/aclocal/intltool.m4:160: IT_PROG_INTLTOOL is expanded from...
configure.ac:40: the top level
autoreconf: configure.ac: tracing
autoreconf: configure.ac: AM_GNU_GETTEXT is used, but not AM_GNU_GETTEXT_VERSION
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/local/Cellar/autoconf/2.69/bin/autoconf --force
configure.ac:24: error: possibly undefined macro: AC_MSG_ERROR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/local/Cellar/autoconf/2.69/bin/autoconf failed with exit status: 1
```

I'm not quite sure what is missing now, because the `gettext.m4` file is already copied in. I think someone more proficient with Mac OS X would have to look at this issue though. Patches are welcome...

Regards

**Comment by delacost** [comment]
I experienced the same output :/ If I were experienced enough to patch something like I would love to contribute, but my devel expertise simply isn't sufficient ..
