### ISSUE TITLE
Support password in MPD_HOST environment variable

### ISSUE THREAD

**Issue by dsonck92** [ambientsound/pms#36]
Various MPD clients currently use `MPD_HOST` for both password and host store. Although I personally agree that `MPD_HOST` + `MPD_PASSWORD` is better, it might be best to **IF** `MPD_HOST` contains an `@` character, it follows the `<password>@<host>` format. This allows users to use either format. It's also a safe assumption as the host should not contain `@` in the name

**Comment by ambientsound** [comment]
I agree that PMS should support the password in `MPD_HOST`. All the same, supporting both is added complexity and might be confusing for the user. I suggest that `MPD_PASSWORD` is dropped altogether, breaking backwards compatibility but reducing ambiguity.

**Comment by dsonck92** [comment]
I see this was actually implemented some time ago already? So I guess that this is more of a reminder to remove the old way. I was using a rather old release apparently that even had issues with consume mode. Which has been resolved in the current master branch.

**Comment by tremby** [comment]
This should apply to the Go version too.

**Comment by ambientsound** [comment]
Yes, the Go version should support passwords in `MPD_HOST`. The issue name is misleading, since the Go version does not support `MPD_PASSWORD` at all.
