### ISSUE TITLE
Running add-album on an album already in the queue causes segfault

### ISSUE THREAD

**Issue by mpnordland** [ambientsound/pms#37]
When I select a song and run add-album, if song(s) from that album are already in the queue pms gives a segfault.

**Comment by tremby** [comment]
Yikes! I'm getting this too.

**Comment by tremby** [comment]
@mpnordland: I've just opened a pull request with a fix for this issue. Would be great if you could test it.

**Comment by ambientsound** [comment]
@tremby, I tested your pull request and it seems to work fine.

**Comment by mpnordland** [comment]
I will try and test this when I get home, it's been a while since I had pms installed.

---- On Fri, 21 Apr 2017 01:07:17 -0400 notifications@github.com wrote ----

@mpnordland: I've just opened a pull request with a fix for this issue. Would be great if you could test it.

**Comment by tremby** [comment]
Don't feel you need to; Kim and I both tested.
