### ISSUE TITLE
Assertion fail - PMS stops

### ISSUE THREAD

**Issue by z3bu** [ambientsound/pms#47]
When launching a freshly built PMS I get this error:

> 
> Stopped.                                                                                                                                                                              2017-04-20 00:51:41 /status/ Stopped.
>                                   2017-04-20 00:51:41 /debug/ --> Main loop iteration, clock = 28912.497969553
>                                                                                                               2017-04-20 00:51:41 /debug/ Retrieving MPD status from server.
>                                                                                                                                                                             2017-04-20 00:51:41 /debug/ Updating playlist from version -1 to 4
>                                                      pms: /home/z3bu/ambientsound-pms-pre-merge-window-refactor-88-ga774fca/ambientsound-pms-a774fca/src/songlist.cpp:86: Song* Songlist::song(uint32_t): Assertion `position < size()' failed.
>                                                         Aborted (core dumped)

**Comment by ambientsound** [comment]
Hi @z3bu,

Which branch/commit are you on?

**Comment by z3bu** [comment]
Hi, thanks for your answer,
I got the tar archive from the website - I tried the master branch - it is working now.
