### ISSUE TITLE
The add command sometimes gets stuck always adding the same song

### ISSUE THREAD

**Issue by tremby** [ambientsound/pms#54]
Steps to reproduce:

1. Start PMS
2. Switch to library view
3. Add a song with `:add` or a binding
4. Move cursor to a different song
5. Add this song
6. Switch to playlist view, see that the last two songs are the first song you attempted to add, twice

I noticed that selecting a song with `toggle-select` and then `add` gets around the bug, and the next song added with `add` after that will add the correct song too, but then the next after that will be stuck on the previously-added song again.

**Comment by riggs-** [comment]
The legacy branch is no longer maintained, closing for now.
