### ISSUE TITLE
Pressing backspace from an empty command line causes an assertion error

### ISSUE THREAD

**Issue by tremby** [ambientsound/pms#55]
1. Press `:` to start a command line
2. Press backspace

```
src/action.cpp:1214: bool handle_command(pms_pending_keys): Assertion `false' failed.
```

**Comment by PRESFIL** [comment]
Experiencing this on `alacritty`. `pmus-git==0.42.r401.g318d75a-1`

**Comment by riggs-** [comment]
The legacy branch is no longer maintained, closing for now.
