### ISSUE TITLE
[Feature request] Add option to seek forward/backward within tracks

### ISSUE THREAD

**Issue by jottr** [ambientsound/pms#57]
The legacy branch had an option to specify shortcuts to seek forward/backward within tracks, e.g.:
`bind seek +5 ]`.
This is a request to implement it in the go-branch as well.

**Comment by jottr** [comment]
Awesome!
Strangely binding `[]{}` won't work for me: `bind [ seek -5` doesn't register.
Also, `bind <S-left> seek -5` doesn't work. I.e. `Shift <-` to seek backwards.
The debuglog doesn't show anything out of the ordinary.

**Comment by ambientsound** [comment]
Not able to bind `{}[]` looks like a bug in the parser. Not sure if shift is supported yet.

I'll create separate issues for that.
