### ISSUE TITLE
Scroll window but leave cursor alone

### ISSUE THREAD

**Issue by tremby** [ambientsound/pms#65]
I'd like to scroll the window a line up or down while leaving the cursor on the same song it's currently on, like ^E and ^Y in vim.

**Comment by tremby** [comment]
I don't know the best way to approach this one. I'd appreciate some guidance.

**Comment by tremby** [comment]
What should the commands be called? Should they be under `cursor` or not? (They don't actually move the cursor of course.)

**Comment by ambientsound** [comment]
The most difficult problem first (naming): something along the lines of `viewport`, `window`, or `scroll`?

I think this change would concern the widget (`widgets/songlist.go`) and not the list itself. At first glance, I don't see any functions that might support this change, so maybe a new `Scroll(int)` function that moves the visible area?

**Comment by ambientsound** [comment]
Nice addition, thank you.
