### ISSUE TITLE
Resize and refresh does not re-calculate column width and height

### ISSUE THREAD

**Issue by tremby** [ambientsound/pms#88]
After resizing a (urxvt or tmux-in-iterm2) window, PMS doesn't always want to redraw the columns to fill the space, even with ^L.

It seems that changing list back and forth has the necessary effect.

I've noticed the problem more frequently on the library view (which has a lot of very long song titles).

Can you see the same behaviour?

**Comment by ambientsound** [comment]
Yes, I can confirm this behavior. I guess two bugs should be fixed: the `^L` behavior should re-calculate the column widths and window height, _and_ resizing should do this automatically.
