### ISSUE TITLE
PMS hangs sporadically on startup while opening index

### ISSUE THREAD

**Issue by ambientsound** [ambientsound/pms#95]
The last thing seen in the debug log is similar to:

```
[0.39133] Sync(): opening search index
```

Workaround is to delete PMS' cache files:

```
rm -rf ~/.cache/pms/<mpd_host>/<mpd_port>
```

**Comment by tremby** [comment]
I had another hang just now at `Sync(): opening search index`. Waited a long while and nothing appears to be happening. Killed the process and tried again, same thing.

Deleted its cache directory, tried again, it worked.

Loaded again, working.

**Comment by ambientsound** [comment]
This bug might be fixed in #106. @tremby, care to give it a try?

**Comment by tremby** [comment]
Hope so! Due to the sporadic nature I can't be sure just yet, but I will report back if I still get these kind of hangs.

**Comment by ambientsound** [comment]
Thanks. I'll close the issue. Feel free to re-open if if occurs again.
